HarmonIQ/noid

README.md

Update main readme documentation

[Doc] Update main readme documentation

---

source/noid.browser/ProviderBridge.cs
source/noid.html/enrollment.html
source/noid.html/provider.html
source/noid.html/scripts/noid_enrollment.js
source/noid.html/style/noid_enrollment.css

Set overlay div on language and status select, fix queue table view, fix
button show on identity modal, keep modals open until buttons clicked.

Set overlay div on language and status select, fix queue table view, fix button show on identity modal, keep modals open until buttons click

---

source/noid.browser/PatientBridge.cs
source/noid.browser/browserform.cs

- Fix issue with capture site not changing after the reset button
- Fix bug with reset and unknown dob confirmation workflow

Fix issue with capture site not changing after the reset button

---

source/biometrics.fingerprint.database.client/MinutiaCaptureController.cs
source/noid.browser/browserform.cs

- Fix patient UI flow after reset

Fix patient UI flow after reset

---

source/biometric.match.database.engine/DBreezeWrapper.cs
source/biometric.match.database.engine/FingerPrintMatchDatabase.cs
source/biometric.match.database.engine/MinutiaMatch.cs
source/noid.database.mongodb/MongoDBWrapper.cs
source/noid.network.services/PurgeAllDatabases.ashx
source/noid.network.services/PurgeAllDatabases.ashx.cs
source/noid.network.services/SearchBiometrics.ashx.cs
source/noid.network.services/Web.config
source/noid.network.services/noid.network.services.csproj
source/noid.utilities/SecurityUtilities.cs

- Add web service that deletes all MongoDB and DBreeze databases
Example usage:
`PurgeAllDatabases.ashx?destroykey=TsnxNukeqYhtWV....`

Add web service that deletes all MongoDB and DBreeze databases

---

source/noid.browser/PatientBridge.cs
source/noid.browser/ProviderBridge.cs
source/noid.html/enrollment.html
source/noid.html/provider.html
source/noid.html/scripts/noid_enrollment.js

Handle Chrome Auto spell/complete, fix flow issues in Javascript,
Refresh of Approval Queue on apprvroe or deny

Handle Chrome Auto spell/complete, fix flow issues in Javascript, Refresh of Approval Queue on apprvroe or deny

---

source/noid.browser/PatientBridge.cs
source/noid.browser/browserform.cs
source/noid.fhir.profile/PatientFHIRProfile.cs
source/noid.network.services/AddNewPatient.ashx.cs
source/noid.utilities/FHIRUtilities.cs

- Fix bug with sending fingerprint data

Fix bug with sending fingerprint data

---

source/biometric.match.database.engine/DBreezeWrapper.cs

- Fix Delete All Databases Web Service

Fix Delete All Databases Web Service

---

source/noid.browser/PatientBridge.cs
source/noid.browser/browserform.cs
source/noid.fhir.profile/FingerPrintMinutias.cs
source/noid.fhir.profile/PatientFHIRProfile.cs

- Fix bug with not sending minutias after reset

Fix bug with not sending minutias after reset

---

source/noid.fhir.profile/PatientFHIRProfile.cs

- Fix issue with pending list after changes to reset

Fix issue with pending list after changes to reset

---

source/noid.html/error.html

Add Basic Error.html page

---

source/noid.browser/PatientBridge.cs
source/noid.network.services/IdentityChallenge.ashx.cs

Fix identity confirmation step after a reset.

Fix identity workflow after a reset

---

source/noid.browser/PatientBridge.cs
source/noid.browser/ProviderBridge.cs
source/noid.browser/app.config
source/noid.fhir.profile/PatientFHIRProfile.cs
source/noid.network.services/AddNewPatient.ashx.cs
source/noid.utilities/ByteUtilities.cs
source/noid.utilities/FHIRUtilities.cs

- Wire up patient enrolled with no fingers on both hands
- Add dispose method to the ProviderBridge class
- Add regions to better organize the class code:

Wire up patient enrolled with no fingers on both hands

---

source/noid.network.services/UpdatePendingStatus.ashx.cs

- Fix issue with pending queue approve/deny buttons

Fix issue with pending queue approve/deny buttons

---

source/noid.browser/PatientBridge.cs
source/noid.html/enrollment.html
source/noid.html/provider.html
source/noid.html/scripts/noid_enrollment.js

Added No Finger Select, many mods to text, added missing bio info to demographic submission and handling null bridge errormessges for Javascript

Added No Finger Select, many mods to text, added missing bio info to demographic submission

---

source/noid.browser/PatientBridge.cs
source/noid.fhir.profile/PatientFHIRProfile.cs

Fix biometrics capture for the pending queue

Fix biometrics capture for the pending queue

---

source/noid.fhir.profile/PatientFHIRProfile.cs
source/noid.utilities/FHIRUtilities.cs

Add twin indicator code, patient hub/portal credentials, and gender change to FHIR

Add twin indicator code, hub creds, and gender change to FHIR

---

source/noid.browser/PatientBridge.cs
source/noid.browser/ProviderBridge.cs
source/noid.html/enrollment.html
source/noid.html/provider.html
source/noid.html/scripts/noid_enrollment.js

New stubs for patient, auto refresh of queue, javascritp fixes

New stubs for patient, auto refresh of queue, javascritp fixes

---

source/noid.browser/browserform.cs
source/noid.database.mongodb/MongoDBWrapper.cs
source/noid.network.services/SearchBiometrics.ashx.cs

This is to test before merging into master
- Prevent duplicate pending records in the patient queue

Test Prevent duplicate pending records in the patient queue

---

source/noid.browser/browserform.cs
source/noid.database.mongodb/MongoDBWrapper.cs
source/noid.network.services/SearchBiometrics.ashx.cs

- Prevent duplicate pending records in the patient queue

Prevent duplicate pending records in the patient queue

---

source/noid.html/NukeNoIDData_02ae5e0d_98f3_4e5a_a877_7312b74b47be.html
source/noid.html/enrollment.html
source/noid.html/provider.html

Added RegEx to password, exceptionflags to provider, and nuke page

Added RegEx to password, exceptionflags to provider, and nuke page

---

source/noid.browser/PatientBridge.cs
source/noid.browser/app.config
source/noid.browser/browserform.cs
source/noid.database.mongodb/AlternateSearch.cs
source/noid.database.mongodb/MongoDBWrapper.cs
source/noid.database.mongodb/noid.database.mongodb.csproj
source/noid.network.services/AddNewPatient.ashx.cs
source/noid.network.services/AltMatchByDemographics.ashx
source/noid.network.services/AltMatchByDemographics.ashx.cs
source/noid.network.services/noid.network.services.csproj
source/noid.network.transport/DataTransport.cs

- Add stub for alternate search without biometrics

[WIP] Add stub for alternate search without biometrics

---

source/noid.browser/app.config
source/noid.browser/properties/assemblyinfo.cs

Final configuration for CHIME prototype.

Final configuration for CHIME prototype

---

source/noid.html/TestTranslate.html

Add Test Translate Page

---

documentation/diagrams/noid.block.diagram.xml
source/biometrics.fingerprint.devices/DigitalPersona.cs
source/noid.browser/browserform.cs
source/noid.browser/program.cs

Better handling the browser application when in patient mode without a scanner.  Provider kiosk mode will run without a fingerprint scanner.
The application would crash when a fingerprint scanner is not connected.

No scanner
